baseurl = "https://nhutrg1998.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Lê Nhựt"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
publishDir = "nhutrg1998.github.io"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Try not to become a man of success but rather try to become a man of value"
  logo = "img/thumbnail_avt.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/1.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/2.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
[[Params.bigimg]]
  src = "img/hexagon.jpg"
#  desc = "Hexagon"
[[Params.bigimg]]
  src = "img/triangle.jpg"
[[Params.bigimg]]
  src = "img/sphere.jpg"
#[[Params.bigimg]]
#  src = "img/6.jpg"
#[[Params.bigimg]]
#  src = "img/7.jpg"

[Author]
  name = "Lê Nhựt"
  website = "nhutrg1998.github.io"
  facebook = "LNhut98"
  email = "nhutrg1998@gmail.com"
  github = "nhutrg1998"
  
[[menu.main]]
    name = "Blog"
    url = "posts"
    weight = 1

#[[menu.main]]
#    name = "About"
#    url = "page/about/"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
