baseURL = "https://nhutrg1998.github.io/"
languageCode = "en-us"
title = "Lê Nhựt"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "nhutrg1998.github.io"
theme = "ananke"
